---
steps:
  # https://quay.io/repository/coreos/kube-state-metrics?tab=history
  - name: quay.io/coreos/kube-state-metrics:v1.9.1
    args: [lint]
  # https://quay.io/repository/coreos/kube-state-metrics?tab=history
  - name: quay.io/helmpack/chart-testing:v3.9.0
    args: [ct, lint, --all, --debug, --chart-dirs, charts]